OnlineStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages
        {
            get
            {
                return (int) Math.Ceiling((decimal) TotalItems/ItemsPerPage);
            }
            
        }
    }
}

OnlineStore.WebUI/Models/ProductListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using OnlineStore.Domain.Entities;

namespace OnlineStore.WebUI.Models
{
    public class ProductListViewModel
    {
        public IEnumerable<Product> Products { get; set; }

        public PagingInfo PagingInfo { get; set; }

        public string CurrentCategory { get; set; }
    }
}

OnlineStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Domain.Abstract;

namespace OnlineStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private new IProductRepository _repository;

        public NavController(IProductRepository repo)
        {
            _repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = _repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

OnlineStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Domain.Abstract;
using OnlineStore.WebUI.Models;

namespace OnlineStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _repository;
        public int PageSize = 3;

        public ProductController(IProductRepository repo)
        {
            _repository = repo;
        }

        // GET: Product
        public ActionResult List(string category, int page = 1)
        {
            var model = new ProductListViewModel
            {
                Products = _repository.Products
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(x => x.ProductId)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),

                PagingInfo = new PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems =  category == null?
                    _repository.Products.Count():
                    _repository.Products.Count(p => p.Category == category)
                },

                CurrentCategory = category

            };


            return View(model);
        }
    }
}

OnlineStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product", null, new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
{
    controller = "Product",
    action = "List",
    category = link,
    page = 1
},
     new
     {
         @class = "btn btn-block btn-default btn-lg" + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
     }
    )
}

OnlineStore.WebUI/Views/Product/List.cshtml
@model OnlineStore.WebUI.Models.ProductListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach ( var p in Model.Products)
{
    @Html.Partial("ProductSummary",p);
}

<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new {page = x, category = Model.CurrentCategory}))
</div>

OnlineStore.WebUI/Views/Shared/ProductSummary.cshtml
@model OnlineStore.Domain.Entities.Product
    
<div class="well">
    <h3>
        <strong> @Model.Name</strong>
        <span class="pull-right label label-primary"> @Model.Price.ToString("c")</span>
    </h3>
    <span class="lead">@Model.Description</span>

</div>

OnlineStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Store</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>
<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Online Store</a>
</div>
<div class="row panel">
    <div id="categoris" class="col-lg-3">
        @Html.Action("Menu", "Nav");
    </div>
    <div class="col-lg-7">@RenderBody()</div>
</div>
   
</body>
</html>